[build-system]
requires = [
    "setuptools",
    # 4110 only:
     "cython",
     "numpy==1.21.5"
]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
requires-python = ">=3.7"
license = {text = "MIT License"}
name = "instapy"
description = "filter pictures"
readme = "README.md"
dependencies = ["importlib-metadata","numpy","numba","pillow","matplotlib","cython","line_profiler"] 


[project.scripts]
instapy = "instapy.cli:main" # to be able to call instapy with CLI
